version: "3.9"

volumes:
  database-volume:

services:
  postgres:
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: "tmp"
      POSTGRES_USER: "tmp"
      POSTGRES_PASSWORD: "tmp"
    ports:
      - "5432:5432"
    volumes:
      - database-volume:/var/lib/postgresql/data
  server:
    image: raiden454/cpp-app:latest
    volumes:
      - .:/project
    command: make server-run
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
