name: Cpp

on:
  push:
      branches: [ "dev", "main" ]
  pull_request:
      branches: [ "dev", "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    container: raiden454/ddt-project
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          mkdir build
          cd build
          cmake ..
          make
  tests:
    runs-on: ubuntu-latest
    container: raiden454/ddt-project
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Run-Tests
        run: ./build/server/internal/service/tests/test_service
  linters:
    runs-on: ubuntu-latest
    container: raiden454/ddt-project
    steps:
      - uses: actions/checkout@v3
      - name: Cppcheck
        run: |
          cppcheck server --std=c++17 --enable=all
      - name: Cpplint
        run: |
          cpplint --extensions=cpp,hpp,h --recursive ./server/*
