name: Cpp

on:
  push:
      branches: [ "dev", "main" ]
  pull_request:
      branches: [ "dev", "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing
        run: |
          sudo apt update
          git clone https://github.com/google/googletest.git -b release-1.11.0
          cd googletest
          mkdir build
          cd build
          cmake .. -DBUILD_GMOCK=OFF
          make
          sudo make install
          cd ../..
      - name: Building
        run: |
          mkdir build
          cd build
          cmake ..
          make
      # - name: Testing
      #   run: |
      #     ./build/tests/test_parser    
  linters:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Installing
        run: |
          sudo apt update
          sudo apt install cppcheck
          pip install cpplint
      - name: Cppcheck
        run: |
          cppcheck --language=c++ ./src/main.cpp
      - name: Cpplint
        run: |
          cpplint --filter=-legal/copyright,-readability/casting,-whitespace/tab,-build/include_subdir --linelength=110 ./src/main.cpp